__title__ = 'dicomwatch'
__description__ = 'DICOM watcher'
__url__ = 'https://github.com/harvard-nrg/dicomwatch'
__version__ = 'v0.1.0'
__author__ = 'Neuroinformatics Research Group'
__author_email__ = 'info@neuroinfo.org'
